users_input = input("Enter some text: ")
a = users_input.replace("a", "4")
b = a.replace("b", "8")
e = b.replace("e", "3")
l = e.replace("l", "1")
o = l.replace("o", "0")
s = o.replace("s", "5")
t = s.replace("t", "7")
print("Here is your wanky wanky text:", t)
